export const ADD_SUPERHERO_GOOD_TEAM = 'ADD_SUPERHERO_GOOD_TEAM';
export const ADD_SUPERHERO_BAD_TEAM = 'ADD_SUPERHERO_BAD_TEAM';
export const REMOVE_SUPERHERO_GOOD_TEAM = 'REMOVE_SUPERHERO_GOOD_TEAM';
export const REMOVE_SUPERHERO_BAD_TEAM = 'REMOVE_SUPERHERO_BAD_TEAM';
